/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BarStackChart: typeof import('./views/dashboard/chart/BarStackChart.vue')['default']
    BarStackedChartComponent: typeof import('./components/echarts/BarStackedChartComponent.vue')['default']
    BaseChart: typeof import('./components/echarts/BaseChart.vue')['default']
    BaseChartComponent: typeof import('./components/echarts/BaseChartComponent.vue')['default']
    Calendar: typeof import('primevue/calendar')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LineChart: typeof import('./components/echarts/LineChart.vue')['default']
    LineChartComponent: typeof import('./components/echarts/LineChartComponent.vue')['default']
    LineStackChart: typeof import('./components/echarts/LineStackChart.vue')['default']
    LineStackedAreaChart: typeof import('./views/dashboard/chart/LineStackedAreaChart.vue')['default']
    LineStackedChart: typeof import('./views/dashboard/kanban/LineStackedChart.vue')['default']
    Pie: typeof import('./views/dashboard/kanban/Pie.vue')['default']
    PieChart: typeof import('./views/dashboard/chart/PieChart.vue')['default']
    PieChartComponent: typeof import('./components/echarts/PieChartComponent.vue')['default']
    ProjectKanban: typeof import('./views/dashboard/chart/ProjectKanban.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
