/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseChartComponent: typeof import('./components/echarts/BaseChartComponent.vue')['default']
    Calendar: typeof import('primevue/calendar')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Pie: typeof import('./views/dashboard/kanban/Pie.vue')['default']
    PieChart: typeof import('./views/dashboard/kanban/PieChart.vue')['default']
    PieChartComponent: typeof import('./components/echarts/PieChartComponent.vue')['default']
    ProjectKanban: typeof import('./views/dashboard/kanban/ProjectKanban.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
